### ISSUE TITLE
環境変数を指定してデプロイする方法をREADMEに記載する

### ISSUE THREAD

**Issue by keita-nishimoto** [keita-nishimoto/aws-serverless-prototype#7]
## 完了の定義
- 表題の方法がREADMEに記載されている事

**Comment by keita-nishimoto** [comment]
環境変数の指定方法

例えば ```.bash_profile``` に以下のように記述する事で ```serverless.yml``` で以下のような値を取得する事が出来る。

```
export TABLE_PREFIX=dev
```

```
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: globalIndex1
            KeySchema:
              -
                AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${env:TABLE_PREFIX}_Users // dev_Usersが出力される
```

また```serverless.yml``` に環境変数を記載する事も可能。（さっきのとの合わせ技）

```
provider:
  name: aws
  runtime: nodejs4.3
  region: ap-northeast-1
  environment:
    USERS_TABLE_NAME: ${env:TABLE_PREFIX}_Users
```

この場合はソースコードのほうで以下のように取得する事が可能。

```
// "USERS_TABLE_NAME: dev_Users" が出力される
console.log(`USERS_TABLE_NAME: ${process.env.USERS_TABLE_NAME}`);
```
